# Ejercicio

Adaptado de http://www.scipy-lectures.org/index.html

En el fichero `data/populations.txt` se describe la población de liebres, linces y zanahoras en Canada desde 1900 a 1920.

Se pide:
* Calcular la media para cada una de las poblaciones.
* Calcular la desviación estándar para cada una de las poblaciones.
* ¿Qué población tuvo la mayor población cada año?

Recordad, documentación `numpy.ndarray`: https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [1]:
# Podemos ver el fichero directamente con el comando de Jupyter !cat
!cat data/populations.txt

# year	hare	lynx	carrot
1900	30e3	4e3	48300
1901	47.2e3	6.1e3	48200
1902	70.2e3	9.8e3	41500
1903	77.4e3	35.2e3	38200
1904	36.3e3	59.4e3	40600
1905	20.6e3	41.7e3	39800
1906	18.1e3	19e3	38600
1907	21.4e3	13e3	42300
1908	22e3	8.3e3	44500
1909	25.4e3	9.1e3	42100
1910	27.1e3	7.4e3	46000
1911	40.3e3	8e3	46800
1912	57e3	12.3e3	43800
1913	76.6e3	19.5e3	40900
1914	52.3e3	45.7e3	39400
1915	19.5e3	51.1e3	39000
1916	11.2e3	29.7e3	36700
1917	7.6e3	15.8e3	41800
1918	14.6e3	9.7e3	43300
1919	16.2e3	10.1e3	41300
1920	24.7e3	8.6e3	47300


In [2]:
import numpy

In [8]:
data = numpy.loadtxt("data/populations.txt")
print("dimension:", data.ndim)
print("    forma:", data.shape)
print("   tamaño:", data.size)
print("     tipo:", data.dtype)
data

dimension: 2
    forma: (21, 4)
   tamaño: 84
     tipo: float64


array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [8]:
# Calcular la media para cada una de las especies
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [10]:
# Calcular la desviación estándar para cada una de las especies
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [11]:
# ¿Qué especie tuvo la población mayor cada año?
#::GMG::Da los índices de los máximos
populations.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])