# Ejercicio

Adaptado de http://www.scipy-lectures.org/index.html

En el fichero `data/populations.txt` se describe la población de liebres, linces y zanahoras en Canada desde 1900 a 1920.

Se pide:
* Calcular la media para cada una de las poblaciones.
* Calcular la desviación estándar para cada una de las poblaciones.
* ¿Qué población tuvo la mayor población cada año?

Recordad, documentación `numpy.ndarray`: https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [ ]:
# Podemos ver el fichero directamente con el comando de Jupyter !cat
!cat data/populations.txt

In [2]:
import numpy

In [3]:
data = numpy.loadtxt("data/populations.txt")
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [8]:
# Calcular la media para cada una de las especies
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [10]:
# Calcular la desviación estándar para cada una de las especies
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [11]:
# ¿Qué especie tuvo la población mayor cada año?
#::GMG::Da los índices de los máximos
populations.argmax(axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])